eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

server:
    port: 8070

spring:
    application:
        name: schools
    config:
        import: optional:configserver:http://localhost:8888
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/school
        username: postgres
        password: '0000'
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        # properties:
        #     hibernate:
        #         dialect: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
    config:
        students-url: http://localhost:8090/api/v1/students