eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
spring:
    application:
        name: gateway
    config:
        import: optional:configserver:http://localhost:8888
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: students
                  uri: http://localhost:8090
                  predicates:
                      - Path=/api/v1/students/**
                - id: schools
                  uri: http://localhost:8070
                  predicates:
                      - Path=/api/v1/schools/**
    zipkin:
        base-url: http://localhost:9411
    sleuth:
        sampler:
            probability: 1.0
server:
    port: 8222
